### ISSUE TITLE
Load Frida/QBDI into an app with frida-server

### ISSUE THREAD

**Issue by andreafioraldi** [QBDI/QBDI#120]
Hi to all,
I'm writing to load a Frida+QBDI script into an application in the x86_64n Emulator (with root).
Your script uses dlopen to load libQBDI.so (I placed it in /data/local/tmp) but it fails with permission denied.
```
Error: Failed to load /data/local/tmp/libQBDI.so (dlopen failed: couldn't map "/data/local/tmp/libQBDI.so" segment 1: Permission denied)
    at QBDIBinder.load (QBDI/usr/local/share/qbdi/frida-qbdi.js:101:19)
    at QBDIBinder.value [as load] (QBDI/usr/local/share/qbdi/frida-qbdi.js:162:42)
    at Object.<anonymous> (QBDI/usr/local/share/qbdi/frida-qbdi.js:211:37)
    at Object.1 (/script1.js:1672:4)
    at o (../../../../usr/lib/node_modules/frida-compile/node_modules/browser-pack/_prelude.js:1:1)
    at ../../../../usr/lib/node_modules/frida-compile/node_modules/browser-pack/_prelude.js:1:1
    at Object.4../QBDI/usr/local/share/qbdi/frida-qbdi.js (index.js:18:12)
    at o (../../../../usr/lib/node_modules/frida-compile/node_modules/browser-pack/_prelude.js:1:1)
    at r (../../../../usr/lib/node_modules/frida-compile/node_modules/browser-pack/_prelude.js:1:1)
    at ../../../../usr/lib/node_modules/frida-compile/node_modules/browser-pack/_prelude.js:1:1
```
I guess that the target app hasn't the permissions to dlopen things from the system, have you ever tried to do this? Do you know a workaround?

**Comment by romainthomas** [comment]
> I guess that the target app hasn't the permissions to dlopen things from the system

Did you check the SELinux errors in the logcat ?

**Comment by andreafioraldi** [comment]
yep you'r right, I assumed that frida-server disabled selinux to work but it doesn't.
If anyone experience this issue the solution is simply to execute `setenforce 0` as root from adb shell.
