### ISSUE TITLE
Frida does not resume execution after vm.call() (Process crashed: Bad access due to invalid address)

### ISSUE THREAD

**Issue by Olasergiolas** [QBDI/QBDI#258]
**Bug description**
I am having issues with QBDI using the Frida integration to intercept and emulate calls to JNI methods. My problem is pretty similar to #171 where vm.call() does not return, causing a "Process crashed: Bad access due to invalid address" error. As in #171, the function I want to emulate (named "_Z9checkPassP7_JNIEnvP8_jstring"), does actually run properly and reaches its last instruction with the correct value in register X0 (0 if wrong password, 1 if correct). Unfortunately, when the last "ret" instruction is executed to return to the "_Z9checkPassP7_JNIEnvP8_jstring" function, the app crashes with a null pointer dereference (maybe stack top is not properly aligned?).

I already switched the order of `vm.allocateVirtualStack()` and `state.synchronizeContext()` but it still crashes.

**Bug log**
```
0x6cca4d6688    ldp     x29, x30, [sp, #80]
  X0=0x0000000000000000   X1=0x0000006cca4efe02   X2=0x282e38392e3b3e38   X3=0x6f6c6c61003f2e39 
  X4=0x0000000000000018   X5=0x0000000080000000   X6=0x6e6b6b5fff3e2d38   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000006fbc30e000   X9=0x0000000000000000  X10=0x0000000000000001  X11=0x13e5b93f7cf14356 
 X12=0x0000000000000000  X13=0x0000000000000000  X14=0x0000000000000000  X15=0x0000006fbbc13090 
 X16=0x0000006cca4fcd88  X17=0x0000006cca4d62bc  X18=0x0000006fbd08c000  X19=0x0000006e96d1b010 
 X20=0x0000000000000000  X21=0x0000006e96d1b010  X22=0x0000006fbc30e000  X23=0x0000006e96d1b0c8 
 X24=0x0000006d17ecbd80  X25=0x0000006fbc30e000  X26=0x0000006d26cf5000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007feb0142b0   LR=0x000000000000002a   SP=0x0000007feb0141b0 
NZCV=0x0000000060000000   PC=0x0000006cca4d668c 
0x6cca4d668c    add     sp, sp, #96
  X0=0x0000000000000000   X1=0x0000006cca4efe02   X2=0x282e38392e3b3e38   X3=0x6f6c6c61003f2e39 
  X4=0x0000000000000018   X5=0x0000000080000000   X6=0x6e6b6b5fff3e2d38   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000006fbc30e000   X9=0x0000000000000000  X10=0x0000000000000001  X11=0x13e5b93f7cf14356 
 X12=0x0000000000000000  X13=0x0000000000000000  X14=0x0000000000000000  X15=0x0000006fbbc13090 
 X16=0x0000006cca4fcd88  X17=0x0000006cca4d62bc  X18=0x0000006fbd08c000  X19=0x0000006e96d1b010 
 X20=0x0000000000000000  X21=0x0000006e96d1b010  X22=0x0000006fbc30e000  X23=0x0000006e96d1b0c8 
 X24=0x0000006d17ecbd80  X25=0x0000006fbc30e000  X26=0x0000006d26cf5000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007feb0142b0   LR=0x000000000000002a   SP=0x0000007feb014210 
NZCV=0x0000000060000000   PC=0x0000006cca4d6690 
0x6cca4d6690    ret
Process crashed: Bad access due to invalid address

***
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/kenzo/kenzo:6.0.1/MMB29M/V8.2.1.0.MHOCNDL:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-10-08 07:12:31+0000
pid: 13674, tid: 13674, name: entures.allsafe  >>> infosecadventures.allsafe <<<
uid: 10218
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000001  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  00000000000000aa  x7  0000000000000000
    x8  00000000005c0000  x9  0000000000000000  x10 0000000000000000  x11 0000006cbe0d77a0
    x12 0000000000000002  x13 000000000004080f  x14 0000000000020403  x15 0000006cba84fc49
    x16 0000006cba84fc40  x17 0000006fbb802740  x18 0000000000000000  x19 0000007feb012680
    x20 0000000000000000  x21 0000007feb012580  x22 0000007feb012580  x23 0000000000000001
    x24 00000000000002ab  x25 0000006cca5526d6  x26 0000006d111a9870  x27 0000000000000038
    x28 0000006cca5526d2  x29 0000007feb0129d0
    lr  0000006cbaf2a1c4  sp  0000007feb0124c0  pc  0000006cbaf28eac  pst 0000000020000000
backtrace:
      #00 pc 0000000000c4feac  /data/local/tmp/re.frida.server/frida-agent-64.so
      #01 pc 00000000007f8d2c  <anonymous:7fea81a000>
***
[Redmi Note 3::Allsafe ]->

Thank you for using Frida!
```

**Minimal code to reproduce the bug**
App being tested: https://github.com/t0thkr1s/allsafe
Below is the content of my Frida instrumentation script:

```typescript
import {
    VM,
    SyncDirection,
    InstPosition,
    VMAction,
    VMEvent,
    Options
  } from "./frida-qbdi.js";

function qbdiExec(fnc_ptr: NativePointer, ctx: CpuContext, args: InvocationArguments): number{
    var vm = new VM();
    var state = vm.getGPRState();
    var stack = vm.allocateVirtualStack(state, 0x900000);
    state.synchronizeContext(ctx, SyncDirection.FRIDA_TO_QBDI);
    if (vm && vm.version) console.log("QBDI version is " + vm.version.string);
    vm.addInstrumentedModuleFromAddr(fnc_ptr);
    var InstructionCallback = vm.newInstCallback(function (vm, gpr, fpr, data) {
        var inst = vm.getInstAnalysis();
        gpr.dump(); // display the context
        console.log("0x" + inst.address.toString(16) + " " + inst.disassembly); // display the instruction
        return VMAction.CONTINUE;
      });
    var iid = vm.addCodeCB(InstPosition.PREINST, InstructionCallback, null);
    
    var retval = vm.call(fnc_ptr, args);
    console.log("Finished execution inside VM!")
    state.synchronizeContext(ctx, SyncDirection.QBDI_TO_FRIDA);
    return retval.toInt32()
}

function main(){
    const modbase = Process.getModuleByName("libnative_library.so").base
    const fnc_sym = DebugSymbol.fromName("_Z9checkPassP7_JNIEnvP8_jstring")
    const fnc_ptr = fnc_sym.address
    Interceptor.replace(fnc_ptr, new NativeCallback(function(jnienv, jstring): number{
        Interceptor.revert(fnc_ptr);
        Interceptor.flush();

        var retval = qbdiExec(fnc_ptr, this.context, [jnienv, jstring]);

        main()

        return retval;
    }, "int", ["pointer", "pointer"]))
}

main()
```

**Specific command to reproduce the bug**
Command used to compile the script: `frida-compile agent/index.ts -o _agent.js -w`

**Version (please complete the following information):**
- OS: Linux (EndeavourOS)
- Architecture: x64
- QBDI version: 0.11.0
- Frida version: 16.2.1-1
- Python version (for PyQBDI issue): N/A

**Additional context**
N/A

**Comment by nsurbay** [comment]
Hello,

Thanks for your report. I can confirm you that you must do ``synchronizeContext`` before ``allocateVirtualStack``.
Can you confirm that you have exactly the same error (ie, a segfault in ``frida-agent-64.so`` after the last ``ret`` instructions ?

I try to reproduce the issue on my side (with an ARM android), and I have another issue (https://github.com/QBDI/QBDI/issues/243).

**Comment by nsurbay** [comment]
If you get a StackOverflowError Error, can you try to use this function to instrument the function ?

```js
function qbdiExec(fnc_ptr: NativePointer, ctx: CpuContext, args: InvocationArguments): number{
    var vm = new VM();
    var state = vm.getGPRState();

    state.synchronizeContext(ctx, SyncDirection.FRIDA_TO_QBDI);
    var stack = vm.allocateVirtualStack(state, 0x900000);

    if (vm && vm.version) console.log("QBDI version is " + vm.version.string);
    vm.addInstrumentedModuleFromAddr(fnc_ptr);
    var InstructionCallback = vm.newInstCallback(function (vm, gpr, fpr, data) {
        var inst = vm.getInstAnalysis();
        gpr.dump(); // display the context
        console.log("0x" + inst.address.toString(16) + " " + inst.disassembly); // display the instruction
        return VMAction.CONTINUE;
      }); 
    var iid = vm.addCodeCB(InstPosition.PREINST, InstructionCallback, null);
         
    var retval = vm.switchStackAndCall(fnc_ptr, args);
    console.log("Finished execution inside VM!")
    vm.alignedFree(stack);
    return retval.toInt32()
}
```

This function has the followed changed :
* Call ``synchronizeContext`` before ``allocateVirtualStack``
* Use ``vm.switchStackAndCall``. This function will use the stack in gprState.SP (so the one allocated with ``vm.allocateVirtualStack``) for QBDI. When the exchange is perform, gprState.SP will be set with the current stack pointer. This allows the instrumented function to call JNI fonction without triggering the StackOverflowError. The only inconvenient is that QBDI engine and any of your callback will be executed on the allocated stack, and should not call any JNI function (this is not the case here).
* Don't use ``state.synchronizeContext(ctx, SyncDirection.QBDI_TO_FRIDA);``. I'm not sure it's implemented, and, as frida will take care of setting the return value to the state, it's not necessary.
* Use ``vm.alignedFree`` at the end of the function to free our stack (memory leak otherwise)

**Comment by Olasergiolas** [comment]
> Hello,
> 
> Thanks for your report. I can confirm you that you must do `synchronizeContext` before `allocateVirtualStack`. Can you confirm that you have exactly the same error (ie, a segfault in `frida-agent-64.so` after the last `ret` instruction) after switching `synchronizeContext` and `allocateVirtualStack` ?
> 
> I try to reproduce the issue on my side (with an ARM android), and I have another issue (#243).

Exactly as you pointed out, when doing `synchronizeContext` before `allocateVirtualStack` I get an `Error: abort was called`, `java.lang.StackOverflowError: stack size 8192KB`.
```
0x7aa2c10144    ldr     x1, [sp]
  X0=0x0000007bbf4403d0   X1=0x0000000000000000   X2=0x0000000000000000   X3=0x0000007afee023b4 
  X4=0x0000007a83706bb0   X5=0x456c656d656e743b   X6=0x3b746e656d656c45   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000007bbf4403d0   X9=0x0000007aff0b2e90  X10=0x0000000000000000  X11=0x0000000000000001 
 X12=0x85b3fd28e6233109  X13=0x0000000000000fff  X14=0x000000007fe00000  X15=0x0c00000000000000 
 X16=0x0000007aa2c36e38  X17=0x0000007aa2c10124  X18=0x0000007d951d8000  X19=0x0000007c6f443010 
 X20=0x0000000000000000  X21=0x0000007c6f443010  X22=0x0000007d94a74000  X23=0x0000007c6f4430c8 
 X24=0x0000007af03d7d80  X25=0x0000007d94a74000  X26=0x0000007aff3f8000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007a83706e00   LR=0x0000007aa2c0fe48   SP=0x0000007a83706df0 
NZCV=0x0000000060000000   PC=0x0000007aa2c10148 
0x7aa2c10148    mov     x0, x8
  X0=0x0000007bbf4403d0   X1=0x0000000000000000   X2=0x0000000000000000   X3=0x0000007afee023b4 
  X4=0x0000007a83706bb0   X5=0x456c656d656e743b   X6=0x3b746e656d656c45   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000007bbf4403d0   X9=0x0000007aff0b2e90  X10=0x0000000000000000  X11=0x0000000000000001 
 X12=0x85b3fd28e6233109  X13=0x0000000000000fff  X14=0x000000007fe00000  X15=0x0c00000000000000 
 X16=0x0000007aa2c36e38  X17=0x0000007aa2c10124  X18=0x0000007d951d8000  X19=0x0000007c6f443010 
 X20=0x0000000000000000  X21=0x0000007c6f443010  X22=0x0000007d94a74000  X23=0x0000007c6f4430c8 
 X24=0x0000007af03d7d80  X25=0x0000007d94a74000  X26=0x0000007aff3f8000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007a83706e00   LR=0x0000007aa2c0fe48   SP=0x0000007a83706df0 
NZCV=0x0000000060000000   PC=0x0000007aa2c1014c 
0x7aa2c1014c    blr     x9
Error: abort was called
    at _call (agent/frida-qbdi.js:1803)
    at apply (native)
    at call (agent/frida-qbdi.js:1809)
    at qbdiExec (agent/index.ts:25)
    at <anonymous> (agent/index.ts:39)
Process crashed: java.lang.StackOverflowError: stack size 8192KB

***
FATAL EXCEPTION: main
Process: infosecadventures.allsafe, PID: 4052
java.lang.StackOverflowError: stack size 8192KB
        at infosecadventures.allsafe.challenges.NativeLibrary.checkPassword(Native Method)
        at infosecadventures.allsafe.challenges.NativeLibrary.access$checkPassword(NativeLibrary.kt:12)
        at infosecadventures.allsafe.challenges.NativeLibrary$onCreateView$1.onClick(NativeLibrary.kt:26)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7661)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
***
```



> If you get a StackOverflowError, can you try to use this function to instrument the function ?
> 
> ```js
> function qbdiExec(fnc_ptr: NativePointer, ctx: CpuContext, args: InvocationArguments): number{
>     var vm = new VM();
>     var state = vm.getGPRState();
> 
>     state.synchronizeContext(ctx, SyncDirection.FRIDA_TO_QBDI);
>     var stack = vm.allocateVirtualStack(state, 0x900000);
> 
>     if (vm && vm.version) console.log("QBDI version is " + vm.version.string);
>     vm.addInstrumentedModuleFromAddr(fnc_ptr);
>     var InstructionCallback = vm.newInstCallback(function (vm, gpr, fpr, data) {
>         var inst = vm.getInstAnalysis();
>         gpr.dump(); // display the context
>         console.log("0x" + inst.address.toString(16) + " " + inst.disassembly); // display the instruction
>         return VMAction.CONTINUE;
>       }); 
>     var iid = vm.addCodeCB(InstPosition.PREINST, InstructionCallback, null);
>          
>     var retval = vm.switchStackAndCall(fnc_ptr, args);
>     console.log("Finished execution inside VM!")
>     vm.alignedFree(stack);
>     return retval.toInt32()
> }
> ```
> 
> This function has the followed changed :
> 
>     * Call `synchronizeContext` before `allocateVirtualStack`
> 
>     * Use `vm.switchStackAndCall`. This function will use the stack in gprState.SP (so the one allocated with `vm.allocateVirtualStack`) for QBDI. When the exchange is perform, gprState.SP will be set with the current stack pointer. This allows the instrumented function to call JNI fonction without triggering the StackOverflowError. The only inconvenient is that QBDI engine and any of your callback will be executed on the allocated stack, and should not call any JNI function (this is not the case here).
> 
>     * Don't use `state.synchronizeContext(ctx, SyncDirection.QBDI_TO_FRIDA);`. I'm not sure it's implemented, and, as frida will take care of setting the return value to the state, it's not necessary.
> 
>     * Use `vm.alignedFree` at the end of the function to free our stack (memory leak otherwise)

Woah, this totally worked out!! The native function is successfully run by QBDI and the application acts as expected without crashes :tada:.
- QBDI run with wrong password (X0 == 0x0):
```
0x7aa2c15688    ldp     x29, x30, [sp, #80]
  X0=0x0000000000000000   X1=0x0000007aa2c2ee02   X2=0x282e38392e3b3e38   X3=0x6f6c6c61003f2e39 
  X4=0x0000000000000018   X5=0x0000000080000000   X6=0x6e6b6b5fff3e2d38   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000007d94a74000   X9=0x0000000000000000  X10=0x0000000000000001  X11=0x85b3fd28e6233109 
 X12=0x0000000000000000  X13=0x0000000000000000  X14=0x0000000000000000  X15=0x0000007d9462d090 
 X16=0x0000007aa2c3bd88  X17=0x0000007aa2c152bc  X18=0x0000007d951d8000  X19=0x0000007c6f443010 
 X20=0x0000000000000000  X21=0x0000007c6f443010  X22=0x0000007d94a74000  X23=0x0000007c6f4430c8 
 X24=0x0000007af03d7cd0  X25=0x0000007d94a74000  X26=0x0000007aff3f8000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007a81f61040   LR=0x000000000000002a   SP=0x0000007fc2b84fd0 
NZCV=0x0000000060000000   PC=0x0000007aa2c1568c 
0x7aa2c1568c    add     sp, sp, #96
  X0=0x0000000000000000   X1=0x0000007aa2c2ee02   X2=0x282e38392e3b3e38   X3=0x6f6c6c61003f2e39 
  X4=0x0000000000000018   X5=0x0000000080000000   X6=0x6e6b6b5fff3e2d38   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000007d94a74000   X9=0x0000000000000000  X10=0x0000000000000001  X11=0x85b3fd28e6233109 
 X12=0x0000000000000000  X13=0x0000000000000000  X14=0x0000000000000000  X15=0x0000007d9462d090 
 X16=0x0000007aa2c3bd88  X17=0x0000007aa2c152bc  X18=0x0000007d951d8000  X19=0x0000007c6f443010 
 X20=0x0000000000000000  X21=0x0000007c6f443010  X22=0x0000007d94a74000  X23=0x0000007c6f4430c8 
 X24=0x0000007af03d7cd0  X25=0x0000007d94a74000  X26=0x0000007aff3f8000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007a81f61040   LR=0x000000000000002a   SP=0x0000007fc2b85030 
NZCV=0x0000000060000000   PC=0x0000007aa2c15690 
0x7aa2c15690    ret
Finished execution inside VM!
```

- QBDI run with good password (X0 == 0x1):
```
0x7aa2c15688    ldp     x29, x30, [sp, #80]
  X0=0x0000000000000001   X1=0x0000007aa2c2ee0a   X2=0xfffffffffffffffb   X3=0x2e39382e28392e3f 
  X4=0x000000000000000b   X5=0x2e39382e28392e3f   X6=0x6e6b6b5fff3e2d38   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000007d94a74000   X9=0x0000000000000000  X10=0x0000000000000001  X11=0x85b3fd28e6233109 
 X12=0x0000000074657263  X13=0x0000000000000000  X14=0x0000000000000000  X15=0x0000007d9462d090 
 X16=0x0000007aa2c3bd88  X17=0x0000007aa2c152bc  X18=0x0000000000000000  X19=0x0000007c6f443010 
 X20=0x0000000000000000  X21=0x0000007c6f443010  X22=0x0000007d94a74000  X23=0x0000007c6f4430c8 
 X24=0x0000007af03d7cd0  X25=0x0000007d94a74000  X26=0x0000007aff3f8000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007a81769040   LR=0x000000000000002a   SP=0x0000007fc2b84fd0 
NZCV=0x0000000060000000   PC=0x0000007aa2c1568c 
0x7aa2c1568c    add     sp, sp, #96
  X0=0x0000000000000001   X1=0x0000007aa2c2ee0a   X2=0xfffffffffffffffb   X3=0x2e39382e28392e3f 
  X4=0x000000000000000b   X5=0x2e39382e28392e3f   X6=0x6e6b6b5fff3e2d38   X7=0x7f7f7f7f7f7f7f7f 
  X8=0x0000007d94a74000   X9=0x0000000000000000  X10=0x0000000000000001  X11=0x85b3fd28e6233109 
 X12=0x0000000074657263  X13=0x0000000000000000  X14=0x0000000000000000  X15=0x0000007d9462d090 
 X16=0x0000007aa2c3bd88  X17=0x0000007aa2c152bc  X18=0x0000000000000000  X19=0x0000007c6f443010 
 X20=0x0000000000000000  X21=0x0000007c6f443010  X22=0x0000007d94a74000  X23=0x0000007c6f4430c8 
 X24=0x0000007af03d7cd0  X25=0x0000007d94a74000  X26=0x0000007aff3f8000  X27=0x0000000000000002 
 X28=0x0000000000000001   FP=0x0000007a81769040   LR=0x000000000000002a   SP=0x0000007fc2b85030 
NZCV=0x0000000060000000   PC=0x0000007aa2c15690 
0x7aa2c15690    ret
Finished execution inside VM!
```

**Comment by Olasergiolas** [comment]
This can now be closed :+1:. Hopefully in the future this behavior is documented somewhere since I was trying to follow ["Why are Frida and QBDI a Great Blend on Android? "](https://blog.quarkslab.com/why-are-frida-and-qbdi-a-great-blend-on-android.html) as a reference.
